version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
  app:
    build:
      context: .
    command: >
      sh -c "sleep 10 &&
             node src/migrate.ts &&
             node src/index.ts"
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - AWS_REGION=local
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    volumes:
      - .:/app

volumes:
  dynamodb_data:
