services:
  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    container_name: dynamodb
    ports:
      - "8000:8000"
  app:
    build:
      context: .
    command: sh -c "sleep 5 && node src/migrate.ts && node src/index.ts"
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - AWS_REGION=local
    volumes:
      - .:/app

volumes:
  dynamodb_data:
